/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AddHabitCommand {
  description: string;
  icon: string;
  name: string;
  positive: boolean;
}
