/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUsermanagementAccountLoginPost } from '../fn/account/api-usermanagement-account-login-post';
import { ApiUsermanagementAccountLoginPost$Params } from '../fn/account/api-usermanagement-account-login-post';
import { apiUsermanagementAccountRegisterPost } from '../fn/account/api-usermanagement-account-register-post';
import { ApiUsermanagementAccountRegisterPost$Params } from '../fn/account/api-usermanagement-account-register-post';

@Injectable({ providedIn: 'root' })
export class AccountService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsermanagementAccountRegisterPost()` */
  static readonly ApiUsermanagementAccountRegisterPostPath = '/api/usermanagement/Account/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsermanagementAccountRegisterPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsermanagementAccountRegisterPost$Response(params: ApiUsermanagementAccountRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUsermanagementAccountRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsermanagementAccountRegisterPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsermanagementAccountRegisterPost(params: ApiUsermanagementAccountRegisterPost$Params, context?: HttpContext): Observable<void> {
    return this.apiUsermanagementAccountRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiUsermanagementAccountLoginPost()` */
  static readonly ApiUsermanagementAccountLoginPostPath = '/api/usermanagement/Account/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsermanagementAccountLoginPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsermanagementAccountLoginPost$Response(params: ApiUsermanagementAccountLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiUsermanagementAccountLoginPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsermanagementAccountLoginPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiUsermanagementAccountLoginPost(params: ApiUsermanagementAccountLoginPost$Params, context?: HttpContext): Observable<void> {
    return this.apiUsermanagementAccountLoginPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
