/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiHealthCheckHealthCheckGet } from '../fn/health-check/api-health-check-health-check-get';
import { ApiHealthCheckHealthCheckGet$Params } from '../fn/health-check/api-health-check-health-check-get';

@Injectable({ providedIn: 'root' })
export class HealthCheckService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiHealthCheckHealthCheckGet()` */
  static readonly ApiHealthCheckHealthCheckGetPath = '/api/HealthCheck/health-check';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthCheckHealthCheckGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthCheckHealthCheckGet$Response(params?: ApiHealthCheckHealthCheckGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHealthCheckHealthCheckGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthCheckHealthCheckGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthCheckHealthCheckGet(params?: ApiHealthCheckHealthCheckGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHealthCheckHealthCheckGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
