/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DeactivateHabitCommand } from '../../models/deactivate-habit-command';

export interface ApiCoreHabitRemoveHabitDelete$Params {
      body: DeactivateHabitCommand
}

export function apiCoreHabitRemoveHabitDelete(http: HttpClient, rootUrl: string, params: ApiCoreHabitRemoveHabitDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiCoreHabitRemoveHabitDelete.PATH, 'delete');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiCoreHabitRemoveHabitDelete.PATH = '/api/core/Habit/remove-habit';
