/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HabitDto } from '../../models/habit-dto';

export interface ApiCoreHabitDataGetHabitsDataGet$Plain$Params {
  dateFrom?: string;
  dateTo?: string;
}

export function apiCoreHabitDataGetHabitsDataGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCoreHabitDataGetHabitsDataGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<HabitDto>>> {
  const rb = new RequestBuilder(rootUrl, apiCoreHabitDataGetHabitsDataGet$Plain.PATH, 'get');
  if (params) {
    rb.query('dateFrom', params.dateFrom, {});
    rb.query('dateTo', params.dateTo, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<HabitDto>>;
    })
  );
}

apiCoreHabitDataGetHabitsDataGet$Plain.PATH = '/api/core/HabitData/get-habits-data';
