/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { HabitDto } from '../../models/habit-dto';
import { RemoveDailyHabitDataCommand } from '../../models/remove-daily-habit-data-command';

export interface ApiCoreHabitDataClearHabitDataPost$Plain$Params {
      body: RemoveDailyHabitDataCommand
}

export function apiCoreHabitDataClearHabitDataPost$Plain(http: HttpClient, rootUrl: string, params: ApiCoreHabitDataClearHabitDataPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<HabitDto>> {
  const rb = new RequestBuilder(rootUrl, apiCoreHabitDataClearHabitDataPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<HabitDto>;
    })
  );
}

apiCoreHabitDataClearHabitDataPost$Plain.PATH = '/api/core/HabitData/clear-habit-data';
