version: '3.9'

services:
  postgresql-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-init:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  bootstrapper:
    build:
      context: ../Backend/
      dockerfile: Bootstrapper.Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Npqsql__ConnectionString=${Npqsql__ConnectionString}
      - Cors__Origin=${Cors__Origin}
    networks:
      - backend-network
      - proxy-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    depends_on:
      postgresql-db:
        condition: service_healthy

  caddy-angular-app:
    build:
      context: ../Frontend/frontend-spa-app
      dockerfile: Frontend.Dockerfile
      args:
        CONFIG: production
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      APP_NAME: ${APP_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config: